### ISSUE TITLE
Cannot Install on Solaris 11.3

### ISSUE THREAD

**Issue by akrambaig** [NullHypothesis/hping3#1]
After issuing 'gmake' cmd following error msgs appears:

root@qual-solaris11-A:/opt/hping3/hping3-20051105# gmake
gcc -c -O2 -Wall   -DUSE_TCL -g  main.c
gcc -c -O2 -Wall   -DUSE_TCL -g  getifname.c
getifname.c: In function ‘get_output_if’:
getifname.c:343:35: warning: pointer targets in passing argument 3 of ‘getsockname’ differ in signedness [-Wpointer-sign]
  if (getsockname(sock_rt, (struct sockaddr *)&iface_out, &len) == -1 ) {
                                   ^
In file included from getifname.c:14:0:
/usr/include/sys/socket.h:517:12: note: expected ‘Psocklen_t’ but argument is of type ‘int *’
 extern int getsockname(int, struct sockaddr *_RESTRICT_KYWD, Psocklen_t);
            ^
getifname.c: In function ‘get_if_name’:
getifname.c:61:11: warning: ‘sa.sin_addr.S_un.S_addr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     printf("DEBUG: Output interface address: %s\n",
           ^
gcc -c -O2 -Wall   -DUSE_TCL -g  getlhs.c
gcc -c -O2 -Wall   -DUSE_TCL -g  parseoptions.c
gcc -c -O2 -Wall   -DUSE_TCL -g  datafiller.c
gcc -c -O2 -Wall   -DUSE_TCL -g  datahandler.c
gcc -c -O2 -Wall   -DUSE_TCL -g  binding.c
gcc -c -O2 -Wall   -DUSE_TCL -g  logicmp.c
gcc -c -O2 -Wall   -DUSE_TCL -g  waitpacket.c
waitpacket.c: In function ‘wait_packet’:
waitpacket.c:546:14: warning: ‘tstamp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  last_tstamp = tstamp;
              ^
waitpacket.c:469:8: note: ‘tstamp’ was declared here
  __u32 tstamp, echo;
        ^
gcc -c -O2 -Wall   -DUSE_TCL -g  sendip.c
gcc -c -O2 -Wall   -DUSE_TCL -g  sendicmp.c
gcc -c -O2 -Wall   -DUSE_TCL -g  sendudp.c
gcc -c -O2 -Wall   -DUSE_TCL -g  sendtcp.c
gcc -c -O2 -Wall   -DUSE_TCL -g  cksum.c
gcc -c -O2 -Wall   -DUSE_TCL -g  statistics.c
gcc -c -O2 -Wall   -DUSE_TCL -g  version.c
gcc -c -O2 -Wall   -DUSE_TCL -g  listen.c
gcc -c -O2 -Wall   -DUSE_TCL -g  sendhcmp.c
gcc -c -O2 -Wall   -DUSE_TCL -g  rtt.c
gcc -c -O2 -Wall   -DUSE_TCL -g  relid.c
gcc -c -O2 -Wall   -DUSE_TCL -g  sendip_handler.c
gcc -c -O2 -Wall   -DUSE_TCL -g  libpcap_stuff.c
In file included from libpcap_stuff.c:20:0:
/usr/include/net/bpf.h:78:8: error: redefinition of ‘struct bpf_program’
 struct bpf_program {
        ^
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /usr/include/pcap.h:45,
                 from libpcap_stuff.c:19:
/usr/include/pcap/bpf.h:107:8: note: originally defined here
 struct bpf_program {
        ^
In file included from libpcap_stuff.c:20:0:
/usr/include/net/bpf.h:258:8: error: redefinition of ‘struct bpf_insn’
 struct bpf_insn {
        ^
In file included from /usr/include/pcap/pcap.h:51:0,
                 from /usr/include/pcap.h:45,
                 from libpcap_stuff.c:19:
/usr/include/pcap/bpf.h:109:9: note: originally defined here
  struct bpf_insn *bf_insns;
         ^
libpcap_stuff.c: In function ‘open_pcap’:
libpcap_stuff.c:26:6: warning: variable ‘on’ set but not used [-Wunused-but-set-variable]
  int on;
      ^
libpcap_stuff.c: In function ‘pcap_recv’:
libpcap_stuff.c:61:19: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
                 p = (unsigned char*) pcap_next(pcapfp, &hdr);
                   ^
gmake: *** [libpcap_stuff.o] Error 1

**Comment by NullHypothesis** [comment]
If you have troubles compiling hping3, I suggest you get in touch with the maintainers. I'm just providing a tiny patch here and I have no affiliation with hping3. Sorry that I cannot be of more help.
